center-for-threat-informed-defense/attack-workbench-rest-api

app/config/allowed-values.json
package-lock.json
package.json

Add allowed values for collection layers and platforms, for data source objects.
Also update the version of mongoose to fix a Snyk (vulnerability) warning.

Add allowed values for collection layers and platforms

---

.eslintrc.yml
app/controllers/collection-bundles-controller.js
app/controllers/system-configuration-controller.js
app/services/collection-bundles-service.js
app/services/stix-bundles-service.js
app/services/system-configuration-service.js
app/tests/api/stix-bundles/stix-bundles.spec.js

Also filters x_mitre_data_sources for ics techniques, only allowing data sources that are listed in the allowed values.

Derive x_mitre_data_sources for enterprise techniques

---

app/services/matrices-service.js

Use the provided STIX ID, if applicable, when creating a new matrix

Matrix STIX ID Bug Fix

---

app/controllers/user-accounts-controller.js
app/services/user-accounts-service.js

Adds a default role of 'none' to newly registered users.

Add default role for registered users

---

app/api/definitions/components/system-configuration.yml
app/api/definitions/openapi.yml
app/api/definitions/paths/system-configuration-paths.yml
app/controllers/system-configuration-controller.js
app/models/system-configuration-model.js
app/routes/system-configuration-routes.js
app/services/system-configuration-service.js
app/tests/api/system-configuration/system-configuration.spec.js

Add organization namespace endpoints, with tests.

---

app/models/group-model.js
app/models/matrix-model.js
app/models/relationship-model.js

Move Relationship Objects to their own Collection

---

app/services/stix-bundles-service.js

When exporting a STIX bundle, use external_references to determine Matrix domain

---

app/services/stix-bundles-service.js

Include relationships between primary objects when exporting a STIX bundle

---

app/api/definitions/paths/relationships-paths.yml
app/controllers/relationships-controller.js
app/services/attack-objects-service.js
app/services/identities-service.js
app/services/relationships-service.js
app/tests/api/attack-objects/attack-objects.spec.js

Fix: GET /api/attack-objects must include Relationship objects

---

app/lib/authn-middleware.js

Check the authorization scheme to determine which authentication method to use.
Closes #188

Fix Error in Basic APIKEY Authentication

---

app/services/collection-bundles-service.js
app/services/stix-bundles-service.js
app/tests/api/stix-bundles/stix-bundles.spec.js
scripts/clearDatabase.js

Also add relationship collection to clear database script.

Fix error with ICS domain name.

---

resources/sample-configurations/multiple-apikey-services.json
resources/sample-configurations/navigator-basic-apikey.json

Summary of changes:
- Added sample resource `navigator-basic-apikey.json` to configure the Navigator to authenticate with the REST API
- Added sample resource `multiple-apikey-services.json` to configure both the Navigator and the Collection Manager to authenticate with the REST API

nav integration docs

---

app/models/reference-model.js
app/tests/api/references/references.spec.js

Searching for references now includes the source_name in the search

Added source_name to the search

---

app/api/definitions/paths/tactics-paths.yml
app/api/definitions/paths/techniques-paths.yml
app/controllers/tactics-controller.js
app/controllers/techniques-controller.js
app/services/tactics-service.js
app/services/techniques-service.js
app/tests/api/tactics/tactics.techniques.spec.js
app/tests/api/techniques/techniques.tactics.json
app/tests/api/techniques/techniques.tactics.spec.js

Add endpoints to retrieve tactics for a techniques and techniques for a tactic

---

app/api/definitions/paths/data-sources-paths.yml
app/api/definitions/paths/mitigations-paths.yml
app/api/definitions/paths/software-paths.yml
app/api/definitions/paths/tactics-paths.yml
app/api/definitions/paths/techniques-paths.yml
app/controllers/data-sources-controller.js
app/controllers/mitigations-controller.js
app/controllers/software-controller.js
app/controllers/tactics-controller.js
app/controllers/techniques-controller.js
app/services/data-sources-service.js
app/services/mitigations-service.js
app/services/software-service.js
app/services/tactics-service.js
app/services/techniques-service.js
app/tests/api/techniques/techniques.query.spec.js

Search on domain for:
- data sources
- mitigations
- software
- tactics
- techniques
Search on platform for:
- data sources
- software
- techniques

Add search on domain and platform when retrieving all objects of applicable types

---

app/services/stix-bundles-service.js
package-lock.json
package.json

When exporting a group or campaign, derive the domains from related objects

---

app/services/stix-bundles-service.js

- Don't use deprecated relationships when backfilling x_mitre_data_sources.
- Backfill x_mitre_data_sources for ICS using the same logic as for Enterprise.
Closes #232

Fix problems with backfilling x_mitre_data_sources

---

app/models/mitigation-model.js
app/services/stix-bundles-service.js
app/tests/api/mitigations/mitigations.spec.js
package-lock.json
package.json

`labels` property
- Adds `labels` property to the Mitigation object's schema as a String array.
- When exporting a STIX bundle, removes the `labels` property if it is empty.
- Modifies API tests to check this new property.
- Bumps the ATT&CK Spec Version (minor, non-breaking change)
Also updates a couple of modules to remove security vulnerabilities.

Add labels property to Mitigations

---

app/api/definitions/components/techniques.yml
app/models/subschemas/attack-pattern.js
app/tests/api/techniques/techniques.spec.js

Also modified OpenAPI technique definition to match technique data model.
Sorted properties in both to make tracking properties easier.
Closes #243

Add support for x_mitre_network_requirements

---

.github/workflows/ci-workflow.yml

Fix build pipeline

---

app/config/allowed-values.json

Fix allowed values for collection layers.

---

.github/workflows/ci-workflow.yml
package-lock.json
package.json

Also remove unneeded codecov dependency.
Closes #253

Update codecov action to v3

---

app/services/attack-objects-service.js
app/services/campaigns-service.js
app/services/collection-bundles-service.js
app/services/collections-service.js
app/services/data-components-service.js
app/services/data-sources-service.js
app/services/groups-service.js
app/services/identities-service.js
app/services/matrices-service.js
app/services/mitigations-service.js
app/services/notes-service.js
app/services/software-service.js
app/services/stix-bundles-service.js
app/services/tactics-service.js
app/services/techniques-service.js
app/tests/api/collections/collections.spec.js

Modify the retrieveAll() sort direction to match the index.

---

app/api/definitions/openapi.yml
app/api/definitions/paths/health-paths.yml
app/controllers/health-controller.js
app/routes/health-routes.js
app/services/stix-bundles-service.js

Also adds additional properties to the list of properties to check for zero length arrays when exporting STIX bundles.
Closes #317

Add Health Check Endpoints

---

app/controllers/assets-controller.js
app/services/assets-service.js
app/services/collection-bundles-service.js

Adds support for importing assets.
Closes #311

Add support for importing assets.
