app/api/definitions/components/data-components.yml, app/api/definitions/components/data-sources.yml, app/api/definitions/components/stix-common.yml, app/api/definitions/openapi.yml, app/api/definitions/paths/data-components-paths.yml, app/api/definitions/paths/data-sources-paths.yml, app/api/definitions/paths/relationships-paths.yml, app/controllers/data-components-controller.js, app/controllers/data-sources-controller.js, app/models/data-component-model.js, app/models/data-source-model.js, app/models/subschemas/stix-core.js, app/routes/data-components-routes.js, app/routes/data-sources-routes.js, app/services/collection-bundles-service.js, app/services/data-components-service.js, app/services/data-sources-service.js, app/services/relationships-service.js, app/tests/api/data-components/data-components-pagination.spec.js, app/tests/api/data-components/data-components.spec.js, app/tests/api/data-sources/data-sources-pagination.spec.js, app/tests/api/data-sources/data-sources.spec.js, app/tests/import/collection-bundles-enterprise.spec.js, docs/data-model.md, scripts/clearDatabase.js, scripts/loadBundle.js
Adds endpoints for data sources and data components.
```
GET /api/data-sources
POST /api/data-sources
GET /api/data-sources/{stidId}
GET /api/data-sources/{stidId}/modified/{modified)
PUT /api/data-sources/{stidId}/modified/{modified)
DELETE /api/data-sources/{stidId}/modified/{modified)
```
```
GET /api/data-components
POST /api/data-components
GET /api/data-components/{stidId}
GET /api/data-components/{stidId}/modified/{modified)
PUT /api/data-components/{stidId}/modified/{modified)
DELETE /api/data-components/{stidId}/modified/{modified)
```
Updates the import collection endpoint to also import data sources and data components.
Minor bump of Mongoose module version to remove security warning.
=> Add data sources and data components endpoints

.nycrc, package.json
Configure nyc to include all Javascript files in the `app` directory in coverage reports, but exclude test files.
Also Remove the import test from the list of standard tests.
Closes #139
=> Modify the nyc coverage configuration

app/api/definitions/components/user-accounts.yml, app/models/user-account-model.js, app/services/user-accounts-service.js, app/tests/api/user-accounts/user-accounts.spec.js
Add `created` and `modified` timestamps to the user account model and set them automatically in the user account service.
Closes #149
=> Add created and modified timestamps to the user account model

app/api/definitions/paths/system-configuration-paths.yml, app/controllers/system-configuration-controller.js, app/services/system-configuration-service.js, app/tests/api/system-configuration/system-configuration.spec.js, package-lock.json, package.json
When the `GET /api/config/default-marking-definitions` endpoint is unable to retrieve the marking definition object, include the STIX ID of the missing object in the log.
Enable the `refOnly` query parameter for the same endpoint.
Add a test for the `refOnly` query parameter.
Closes #160
=> Provide better debugging info when getting the Default Marking Definitions

app/services/data-sources-service.js, app/services/groups-service.js, app/services/mitigations-service.js, app/services/software-service.js, app/services/tactics-service.js, app/services/techniques-service.js, app/tests/api/groups/groups.query.json, app/tests/api/groups/groups.query.spec.js, app/tests/api/techniques/techniques.spec.js
Adds the `workflow.attack_id` property when searching the techniques, tactics, software, mitigations, groups, and data sources endpoints.
=> Expand search to include the ATT&CK ID stored in the attack_id field

app/api/definitions/paths/stix-bundles-paths.yml, app/controllers/stix-bundles-controller.js, app/lib/linkById.js, app/services/stix-bundles-service.js, app/tests/api/stix-bundles/stix-bundles.spec.js, package-lock.json, package.json
Groups are now secondary objects
x_mitre_domain is filled in for groups
Objects missing an ATT&CK ID are not included in the bundle
LinkById tags are converted to markdown references
Closes #94 
Implements STIX bundle part of #168 
Implements STIX bundle part of #133
=> Modify the STIX bundle export

app/config/config.js, app/lib/linkById.js, app/models/attack-object-model.js, app/services/collection-bundles-service.js, app/services/stix-bundles-service.js
Also moves the list of ATT&CK `source_name` values to a shared location.
=> Convert LinkById tags to Markdown Links when Exporting a Collection Bundle

app/services/stix-bundles-service.js, app/tests/import/collection-bundles-enterprise.spec.js, package-lock.json, package.json
The STIX standard doesn't allow empty arrays. When exporting a STIX bundle, remove empty arrays for these properties:
- `x_mitre_contributors`
- `x_mitre_platforms`
- `x_mitre_aliases`
- `x_mitre_domains`
=> Remove empty arrays when exporting a STIX bundle.

app/services/stix-bundles-service.js
Delete empty arrays for additional properties. Simplify the code structure while doing that.
=> Delete empty arrays when exporting Stix bundles.

app/api/definitions/paths/references-paths.yml, app/controllers/references-controller.js, app/routes/references-routes.js, app/services/references-service.js, app/tests/api/references/references.spec.js
Adds the endpoint:
```
DELETE /api/references?sourceName=mySourceName
```
which deletes the reference with the provided `sourceName`.
Note that this endpoint does not check for ATT&CK objects that might cite the reference or ATT&CK objects that have been published. Those can be added in later if necessary.
Closes #199
=> Add an endpoint that deletes a reference.

app/config/allowed-values.json, app/lib/database-connection.js, app/lib/database-in-memory.js, app/services/collection-bundles-service.js, app/services/collection-indexes-service.js, app/services/collections-service.js, app/services/data-components-service.js, app/services/data-sources-service.js, app/services/groups-service.js, app/services/identities-service.js, app/services/marking-definitions-service.js, app/services/matrices-service.js, app/services/mitigations-service.js, app/services/notes-service.js, app/services/references-service.js, app/services/relationships-service.js, app/services/software-service.js, app/services/tactics-service.js, app/services/techniques-service.js, app/services/user-accounts-service.js, app/tests/api/groups/groups.spec.js, package-lock.json, package.json
Add `Containers` to the list of allowed values for Enterprise techniques and software.
Migrate to Mongoose 6 (fixes snyk error).
Closes #211
=> Add Containers to allowed Platforms; Migrate to Mongoose 6

app/api/definitions/paths/attack-objects-paths.yml, app/controllers/attack-objects-controller.js, app/services/attack-objects-service.js, app/tests/api/attack-objects/attack-objects-1.json, app/tests/api/attack-objects/attack-objects-2.json, app/tests/api/attack-objects/attack-objects.spec.js
=> Add the option to return all versions of objects to the GET /api/attack-objects endpoint

app/config/config.js, app/lib/migration/migrate-database.js, app/lib/migration/migration-config.js, bin/www, migrations/20220705205741-move-relationships.js, migrations/sample-migration.js, package-lock.json, package.json
Add support for migration scripts that run when the REST API service starts up. Track which migration scripts have been applied.
Closes #181
=> Support migration scripts

app/services/data-sources-service.js, app/tests/api/data-sources/data-sources.spec.js
When retrieving data sources with the `retrieveDataComponents=true` query parameter, the data source service adds related data components to the result. This PR modifies the service to include deprecated and revoked data components when adding related data components to the data source.
Closes #242
=> Retrieve deprecated and revoked data components for the selected data source

README.md, app/services/recent-activity-service.js, package-lock.json, package.json
Adds documentation on how to configure Workbench to use OIDC for authenticating users.
Also fixes some lint warnings.
Closes #283
=> Document Configuring OIDC for User Authentication

app/services/_base.service.js
=> Add late binding to the base service.

app/services/matrices-service.js
Fixes an issue with retrieving tactics and techniques within a matrix when it contains tactics with duplicate names.
The matrix service builds the matrix by tactic, sequentially retrieving each tactic object and its techniques, and then maps the tactics by name (rather than by a unique ID). This causes subsequent tactics to be re-mapped/overwrite previous tactics with the same name and the matrix does not build as expected on the front end (appearing to have missing tactics/techniques).
=> Bug fix: duplicate names in matrix tactics

README.md, app/config/config.js, app/index.js, app/tests/shared/keycloak.js
=> feat: implement support for CORS allow-list

app/exceptions/index.js, app/repository/attack-objects-repository.js, app/repository/recent-activity-repository.js, app/services/attack-objects-service.js, app/services/recent-activity-service.js
Admittedly, I don't love the `RecentActivityRepository` implementation.
Concerns:
* It doesn't exactly follow the mold/standard convention of the other services. For one, it is not extending `BaseRepository`
* It's essentially just a bucket for a single, edge-base  method (`retrieveAll`) that calls both the `AttackObject` and `Relationship` Mongoose models. I feel like we should be able to do this by chaining together a few calls to `attackObjectsService` and `relationshipsService`.
But I can't think of a more graceful solution at the moment, and this is still a step forward
=> 295 refactor recent activity service for improved structure and asynchronicity

app/services/recent-activity-service.js, app/tests/api/recent-activity/recent-activity.spec.js, app/tests/api/recent-activity/sample-collection.json
I fixed the issue and added some very basic tests just to make sure the service is working. Those tests should probably be revisited at some point. The standard pagination suite couldn't be used, because it expects to start with an empty array, and recent activity is never empty because the placeholder identity gets created right away.
=> 380 bug: GET/api/recent-activity returns 500

app/services/stix-bundles-service.js
This fixes two regressions in project-orion:
- LinkById resolution during STIX bundle export
- Remove empty arrays
=> 382 bug stix bundle export
